name: chkobba
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fluffu_logo.png
    - assets/fluffy_normal.png
    - assets/fluffy_happy.png
    - assets/fluffy_sad.png
    - assets/fluffy_confused1.png
    - assets/fluffy_confused2.png
    - assets/fluffy_icon.png
  fonts:
    - family: Risque
      fonts:
        - asset: assets/fonts/Risque-Regular.ttf
